### ISSUE TITLE
NPE in setApplicationUrl using POJO construction

### ISSUE THREAD

**Issue by jmkgreen** [spring-projects/spring-social#129]
This was working fine in 1.0.3.

```
ProviderSignInController controller = new ProviderSignInController(connectionFactoryLocator,
usersConnectionRepository, new SpringSecuritySignInAdapter(userBean, userService, preferencesRepository, regCode));
 controller.setApplicationUrl(this.applicationUrl);
```

Pretty much as per your documentation, wrapped in a method annotated `@Bean` and in a class annotated `@Configuration`.

I did not now expect the following stacktrace:

```
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public org.springframework.social.connect.web.ProviderSignInController com.mjog.portal.spring.social.config.SpringControllerFactory.providerSignInController()] threw exception; nested exception is java.lang.NullPointerException
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:181)
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:586)
... 48 more
Caused by: java.lang.NullPointerException
at org.springframework.social.connect.web.ProviderSignInController.setApplicationUrl(ProviderSignInController.java:142)
```

(Our boring code omitted).

Basically `setApplicationUrl()` now expects `afterPropertiesSet()` to have been already called. Within POJO construction this is not the case.

Unable to proceed, unless I've again got something badly misunderstood here.

**Comment by sumit784** [comment]
Did anyone fixed it.. This is probably the reason why I am getting incorrect URI errors on "Google & Linkedin" . 

any timeline for fixing this ?

**Comment by AtRow** [comment]
I had to fix it like this:
```
@Bean(initMethod = "workaroundInit")
public ConnectController connectController(
        ConnectionFactoryLocator connectionFactoryLocator,
        ConnectionRepository connectionRepository) {

    return new ConnectController(connectionFactoryLocator, connectionRepository) {
        // Workaround for issue: https://github.com/spring-projects/spring-social/issues/129
        public void workaroundInit() {
            setApplicationUrl(applicationUrl);
         }
    };
}
```

**Comment by juanromanf** [comment]
Other workaround for ConnectController ( v1.1.0-RELEASE)

```java
    @Bean
    public ConnectController connectController(ConnectionFactoryLocator connectionFactoryLocator, ConnectionRepository connectionRepository) throws Exception {
    	
        ConnectController connectController = new ConnectController(connectionFactoryLocator, connectionRepository);
        connectController.afterPropertiesSet();
        connectController.setApplicationUrl(applicationURL);
        
        return connectController;
    }
```
